version: '3.8'

services:
  # MCP Tools 应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-tools-app
    restart: unless-stopped
    working_dir: /var/www/html/laravel
    volumes:
      - ./laravel:/var/www/html/laravel
    ports:
      - "34004:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/laravel/database/database.sqlite
    networks:
      - mcp-network

volumes:
  app_data:
    driver: local

networks:
  mcp-network:
    driver: bridge
