version: '3.8'

services:
  # MCP Tools 应用服务 (Apache + PHP 8.2)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-tools-app
    restart: unless-stopped
    working_dir: /data/dongasai/mcp_tools/
    volumes:
      - .:/data/dongasai/mcp_tools/
      - ./docker/supervisord.local.conf:/etc/supervisor/conf.d/laravel.conf
      - ./storage/supervisor/:/var/log/supervisor/
    ports:
      - "34004:80"
      - "34005:34005"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - mcp-network



networks:
  mcp-network:
    driver: bridge
