version: '3.8'

services:
  # MCP Tools 应用服务 (Apache + PHP 8.2)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-tools-run
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./.env:/var/www/html/.env
    ports:
      - "34006:80"


