version: '3.8'

services:
  # MCP Tools 应用服务 (Apache + PHP 8.2)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mcp-tools-app
    restart: unless-stopped
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - .:/var/www/html
      - ./docker/supervisord.dev.conf:/etc/supervisor/conf.d/laravel.conf
    ports:
      - "34004:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    networks:
      - mcp-network



networks:
  mcp-network:
    driver: bridge
