version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    volumes:
      - ..:/workspace
    ports:
      - "34004:34004"
    working_dir: /workspace
    command: tail -f /dev/null